#!/bin/bash

# zyphor install <package-name>

install_package() {
  if [ -z "$2" ]; then
    echo "Zyphor OS: ✖ ERROR"
    echo "Usage: zyphor install <package-name>"
    exit 1
  fi

  apt update &&
  apt install -y "$2"

  echo ""
  echo "Zyphor OS: ✔ DONE"
  echo "Package '$2' done."
  echo ""
}