#!/bin/bash

# zyphor remove <package-name>

remove_package() {
  if [ -z "$2" ]; then
    echo "Zyphor OS: ✖ ERROR"
    echo "Usage: zyphor remove <package-name>"
    exit 1
  fi

  apt remove -y "$2"

  echo ""
  echo "Zyphor OS: ✔ SUCCESS"
  echo "Package '$2' removed."
  echo ""
}