#!/bin/bash

# zyphor help

COMMANDS=(
  "upgrade-everything|Upgrade all system packages to latest versions"
  "clean-everything|Remove unused packages and clean cache"
  "install|Install a package (usage: zyphor install <package-name>)"
  "help|Show available Zyphor commands"
  "remove|Remove a package (usage: zyphor remove <package-name>)"
  "version|Dispay latest Zyphor OS build version"
)

show_help() {
  echo ""
  echo "Zyphor OS Command List"
  echo "----------------------"

  for cmd in "${COMMANDS[@]}"; do
    NAME=$(echo "$cmd" | cut -d '|' -f1)
    DESC=$(echo "$cmd" | cut -d '|' -f2)

    printf "  %-20s %s\n" "$NAME" "$DESC"
  done

  echo ""
}